ARG PORT

FROM node:20.6-alpine

WORKDIR /app

COPY package*.json ./

COPY ssl /app/ssl
RUN chmod 600 /app/ssl/server.key && chmod 644 /app/ssl/server.crt

RUN npm ci

COPY . .

EXPOSE $PORT
EXPOSE $HTTP_PORT

CMD ["npm", "start"]
